### ISSUE TITLE
Unhandled exception when running Structurizr client with .NET Core 3.1.2

### ISSUE THREAD

**Issue by ed-graham** [structurizr/dotnet#66]
My code worked fine with .NET Core 2.2 but is now failing with .NET Core 3.1.  It ran successfully the first time to create the models in the workspace; but every subsequent run (to update the model) fails with the following error:

> C:\Users\grahae\gitrepos\proj\structurizr>dotnet run --framework=netcoreapp3.1
> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
>    at Structurizr.ViewSet.Hydrate()
>    at Structurizr.Workspace.Hydrate()
>    at Structurizr.IO.Json.JsonReader.Read(StringReader reader)
>    at Structurizr.Api.StructurizrClient.GetWorkspace(Int64 workspaceId)
>    at Structurizr.Api.StructurizrClient.PutWorkspace(Int64 workspaceId, Workspace workspace)
>    at Company.Program.Main() in C:\Users\grahae\gitrepos\proj\structurizr\Program.cs:line 25

My `Program.cs` code:

```
    class Program
    {
        private static IConfigurationRoot Configuration;        
        static void Main()
        {
            // read user secrets as part of initial set-up
            var builder = new ConfigurationBuilder();
            builder.AddUserSecrets<Program>();
            Configuration = builder.Build();
            // parse secret values from configuration variables
            long workspaceId = long.Parse(Configuration["Structurizr_WorkspaceId"]);
            string apiKey = Configuration["Structurizr_APIkey"];
            string apiSecret = Configuration["Structurizr_APIsecret"];
            // connect to Structurizr workspace
            StructurizrClient structurizrClient = new StructurizrClient(apiKey, apiSecret);
            // update Structurizr workspace with new diagrams
            structurizrClient.PutWorkspace(workspaceId, proj.Create());
        }
    }
```

My `proj.Create()` method:

```
        public static Workspace Create()
        {
                Workspace workspace = new Workspace("Company Landscape", "A C4 model of the entire Company Landscape.");
                Model model = workspace.Model;
                ViewSet views = workspace.Views;
        
                model.Enterprise = new Enterprise("Company");
        
                // people
                ...
                return workspace;
        }
```

I set my secrets like this:

```
dotnet user-secrets set Structurizr_WorkspaceId STRUCTURIZR_WORKSPACEID
dotnet user-secrets set Structurizr_APIkey STRUCTURIZR_APIKEY
dotnet user-secrets set Structurizr_APIsecret STRUCTURIZR_APISECRET
```

**Comment by ed-graham** [comment]
In case it helps, my `.csproj` file is as follows:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.2;netcoreapp3.1</TargetFrameworks>
    <UserSecretsId>*redacted*</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="2.2.0" />
    <PackageReference Include="Structurizr.Client" Version="0.9.2" />
    <PackageReference Include="Structurizr.Core" Version="0.9.2" />
  </ItemGroup>
</Project>
```

**Comment by simonbrowndotje** [comment]
Perhaps try updating the Structurizr core and client library to 0.9.6 and see if that resolves the issue. If not, let me know the workspace ID (assuming it's on the cloud service), and I can take a look.

**Comment by ed-graham** [comment]
That did the trick, Simon - thank you!
