### ISSUE TITLE
DefaultLayoutMergeStrategy breaks in certain scenarios

### ISSUE THREAD

**Issue by AnnejanBarelds** [structurizr/dotnet#81]
I've been using a locally built version of the Structurizr client (I needed the SoftwareSystemInstance and couldn't wait for the Nuget), and I've since noticed that the DefaultLayoutMergeStrategy sometimes breaks on merging relationships (in method findRelationshipView()). Not fully sure in which scenarios exactly, but obviously in case of a pre-existing view that's undergoing change. It fails on retrieving elements from the elementMap; somehow an element that is expected is not available in the elementMap.

I can simply work around the error by stepping over the offending line and straight to the line that returns null, which leads to the expected result, but that's obviously just a workaround. I could create my own merging strategy to correct this behavior, but I imagine that this is not supposed to happen at all, i.e. it's a bug.

**Comment by simonbrowndotje** [comment]
Any chance of a stack trace?

**Comment by AnnejanBarelds** [comment]
Just triggered it again, paying attention to the scenario. Allow me to elaborate a bit. I have some wrapper code around the actual client that, among other things, replicates the relationships between e.g. containers to also set them between System -> System, System -> Container, and Container -> System. I'm aware the client can do that too, but at the time I worked on this, it did not do so like I wanted it to work. The wrapper also automates the creation of views, so for a System Context View, it will determine which Software Systems to include based on the relations between them.

So now the scenario. When I have pre-existing views, Software System A and B, and Component 1 and 2 belonging to A and having a relationship 1 -> 2, and then move Container 1 from Software System A to Software System B, the error occurs.

More specifically, it's merging the System Context View for B, which had a pre-existing System Context View of which A was not a part. With changing the parent of Component 1 from A to B, a relationship is automatically created B -> A, which causes A to now become part of the System Context View of B. The merging breaks because it loops through the relationships in the updated (local) view, and tries to find the source (B) and destination (A) of that relationship in the elementMap - which, if I understand the code correctly, was filled with elements that are present in both the local and the remote view, and therefore does indeed not contain A.

So not sure if this would also have happened without my wrapper, but I think so. If I'm right, all it takes is a pre-existing System Context view for Software System B, and add another System Context A to that view for which a relationship exists B -> A.

The stacktrace:

   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Structurizr.DefaultLayoutMergeStrategy.findRelationshipView(View viewWithLayoutInformation, Relationship relationshipWithoutLayoutInformation, Dictionary`2 elementMap) in [Redacted]\Structurizr.Core\View\DefaultLayoutMergeStrategy.cs:line 122
   at Structurizr.DefaultLayoutMergeStrategy.CopyLayoutInformation(View viewWithLayoutInformation, View viewWithoutLayoutInformation) in [Redacted]\Structurizr.Core\View\DefaultLayoutMergeStrategy.cs:line 65
   at Structurizr.View.CopyLayoutInformationFrom(View source) in [Redacted]\Structurizr.Core\View\View.cs:line 278
   at Structurizr.ViewSet.CopyLayoutInformationFrom(ViewSet source) in [Redacted]\Structurizr.Core\View\ViewSet.cs:line 407
   at Structurizr.Api.StructurizrClient.PutWorkspace(Int64 workspaceId, Workspace workspace) in [Redacted]\Structurizr.Client\Api\StructurizrClient.cs:line 262
   at [Redacted].UploadWorkspaceToStructurizr(Workspace workspace) in [Redacted]
   at [Redacted].Main(String[] args) in [Redacted]

Error message:

The given key was not present in the dictionary

**Comment by simonbrowndotje** [comment]
Thanks, I've pushed a fix ... let me know if it resolves the problem.

**Comment by AnnejanBarelds** [comment]
Yup, that did the trick. Solved as far as I'm concerned!
